#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9

#bspc monitor DP-0 -d DEV WWW DOC ETC MEDIA


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 1
bspc config window_gap 30
bspc config top_padding 45
bspc config left_padding 45
bspc config right_padding 30
bspc config border_radius 50



feh --bg-fill /home/rjh-mopjones/Downloads/space.png

#bspc config normal_border_color "#F808E9"
#bspc config active_border_color "#13CA91"
#bspc config focused_border_color "#13CA91"

#bspc config normal_border_color "#000000"
bspc config active_border_color "#ff0000"
bspc config focused_border_color "#eaeaea"
panel &
spotify-listener &
xsetroot -cursor_name left_ptr &
bash ~/.config/polybar/launch.sh &
picom
